language: node_js
node_js:
  - '10'
deploy:
  api_key:
    secure: hcuVYsVHwU9gsp2427p+nOv1LuDwhBuZG654EVgAOXP1AMY5ZQiurh5HUL7ja7hUHv/mDmbkOb5ouAMFszVa51vCKL3YripfwQBeKWmRn3OAbXhCM08i5q7IrfehIvc68xgNBm4btKGYyw7zhRycQBNYRBKjHjFKbnpQaijJ3c3FEwvo5owyCTp8b2d3hH72xL4LeOYd4JJXLd59QY/EipIvF09e598MzqGvmHpVqG/X5t56vEEdTOYNt9eWpTPNIKbjExgTcRtCIr7UYEHISBWgNSC+iWtudxL7NQ9GEXhFoG4rz/Ex4mr/h6oyc0WiKv/U3y7AKqg7r8/2wNa8KaDffle7TmgGrwcceBEwJnuUQI51H2pZLAo2Pr5YveBqgb8Bzs6QBKB7tI59YRSa8npUA6Y6N/GxcVWDavI/kmnfmokSkU5PJNQTaUZ5d8iFRry+2Nff5zbrGNqxH2y0yBOvUiO+o5mlkFVyEAvA2Keop8IplmHKseaNnpd3eOHF8MwrXgn4BGbh1jbUAG88W+2HkrRgZOw0hF3It77OcBXVVWGumHBs889ndMjk/OVyPBP6ocYyhqBWvkSo90Q5LptztyFQBxKWzP3mwDQlTN6E2ZoLfbRu8bSSMYqSZigsn4GD3fw+OG4gZ/o7BW4LXtxQubr7qcSzYuFQVgjWSvw=
